/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dDnPXDWEayv
 */
import Link from "next/link";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import MultiFileUpload from "@/app/components/fileUpload/MultiFileUpload";
import { UserButton } from "@clerk/nextjs";

export function FrontPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white w-full">
      <main className="flex-1 flex items-center justify-center bg-gray-100 ">
        <Card className=" max-w-xl mx-4">
          <CardHeader className="text-center">
            <h2 className="text-2xl font-semibold">Upload some files</h2>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center p-1 bg-gray-50 ">
            <MultiFileUpload />
          </CardContent>
        </Card>
      </main>
      <footer className="flex items-center justify-center h-14 border-t">
        <p className="text-sm text-gray-500">
          © Store It. All Rights Reserved.
        </p>
      </footer>
    </div>
  );
}
